# Generated by Django 2.2.12 on 2021-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_password', models.CharField(max_length=64)),
                ('new_password', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetoken', models.TextField()),
                ('devicemodel', models.TextField()),
                ('deviceandroidversion', models.CharField(max_length=200)),
                ('datetimeregister', models.DateTimeField()),
                ('datetimeregisterfa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PingDeviceTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iddevice', models.IntegerField()),
                ('datetimelastonline', models.DateTimeField()),
                ('datetimelastonlinefa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingname', models.CharField(max_length=50)),
                ('settingvalue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SmsInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendernumber', models.CharField(max_length=50)),
                ('smsmessage', models.TextField()),
                ('datetimeen', models.DateTimeField()),
                ('datetimefa', models.CharField(max_length=50)),
                ('iddevice', models.IntegerField()),
            ],
        ),
    ]
